kyutai-labs/moshi

moshi_mlx/requirements.txt
typo
> I, baberabb, confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
=> typo in `moshi_mlx/requirements.txt`

moshi/requirements.txt
=> fix typo in requirements.txt

.github/ISSUE_TEMPLATE/question.yml, .github/actions/moshi_build/action.yml, FAQ.md, README.md, client/package-lock.json, client/package.json, moshi/pyproject.toml, moshi_mlx/README.md, moshi_mlx/pyproject.toml
=> update faq and ci

rust/Cargo.toml, rust/moshi-backend/Cargo.toml, rust/moshi-cli/Cargo.toml, rust/moshi-core/Cargo.toml
just trying on windows, but notice your `profile` config is not working because they are not in workspace root for rust, and so release version wouldn't include symbol and bad for debugging, hence a quick fix
=> fix: make profile actually working

moshi/moshi/server.py
Add the `-ssl` flag to the pytorch server too so that https can be used rather than http.
=> Add the ssl flag to the pytorch server too.

.github/workflows/rust-ci.yml
Install the python dev package for the rust CI.
=> Tweak the CI for libpython.

rust/moshi-backend/config-q8.json, rust/moshi-backend/config.json
Use filenames that match the new repo names so that auto-download works properly. Fixes #129
=> Tweak the model filenames to match the repos.

moshi/moshi/utils/compile.py
Fix minor typo in the error message printed
=> Fix minor typo in compile.py

rust/moshi-core/src/seanet.rs
=> Fix two small issues with seanet layers in streaming mode.

README.md, moshi/moshi/client_gradio.py, moshi/pyproject.toml
> I, @freddyaboulton, confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
Adds a Gradio demo to let developers built web apps with moshi entirely with python
=> Add Gradio Demo

rust/moshi-core/src/lib.rs, rust/moshi-core/src/lm.rs, rust/moshi-core/src/quantized_transformer.rs, rust/moshi-core/src/transformer.rs, rust/moshi-core/src/tts_streaming.rs
=> Merge some internal changes.

rust/moshi-backend/src/stream_both.rs, rust/moshi-core/src/lm_generate_multistream.rs
=> Merge more internal changes.

moshi_mlx/moshi_mlx/models/__init__.py, moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/run_helium.py, rust/moshi-core/src/lm.rs, scripts/import_helium_mlx.py
Add some code to run inference with mlx and a script to convert the weights.
=> Helium inference for MLX

moshi_mlx/moshi_mlx/run_helium.py
=> Quantization support for mlx.

scripts/import_helium_mlx.py, scripts/mimi_streaming_test.py, scripts/moshi_benchmark.py, scripts/quantize_mlx.py
=> Mlx quantized

moshi_mlx/moshi_mlx/models/__init__.py, moshi_mlx/moshi_mlx/models/lm.py, scripts/quantize_mlx.py
=> Add support for 1b-16rvq models.

configs/moshi_7b_202409.json, configs/moshi_dev_2b.json, moshi/moshi/models/loaders.py, moshi/moshi/run_inference.py
=> Add some pytorch batch inference code.

moshi/moshi/conditioners/text.py
=> Raise on unknown conditioning values.

rust/Cargo.toml, rust/mimi-pyo3/Cargo.toml, rust/mimi-pyo3/py_src/rustymimi/__init__.pyi, rust/mimi-pyo3/src/lib.rs, rust/moshi-backend/Cargo.toml, rust/moshi-cli/Cargo.toml
=> Bump the rust version + support for python 3.13.

moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/run_inference.py
=> Use some json configs for MLX.

moshi_mlx/moshi_mlx/models/generate.py, moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/modules/conditioner.py, moshi_mlx/moshi_mlx/run_inference.py
=> Mlx conditioners

moshi_mlx/moshi_mlx/run_inference.py
=> Bump the top-p when sampling.

moshi_mlx/moshi_mlx/run_inference.py, moshi_mlx/moshi_mlx/utils/sampling.py
=> Add topk sampling to the MLX implementation.

moshi_mlx/moshi_mlx/models/generate.py, moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/modules/kv_cache.py, moshi_mlx/moshi_mlx/run_inference.py
=> CFG support for MLX.

moshi/moshi/client_utils.py, moshi/moshi/models/loaders.py, moshi/moshi/run_inference.py, moshi/moshi/server.py
Adding support for reading the config from the repository `config.json` file.
=> Adding configuration read from repos

moshi/moshi/conditioners/base.py, moshi/moshi/models/lm.py, moshi/moshi/models/loaders.py, moshi/moshi/modules/transformer.py, moshi/moshi/run_inference.py, moshi/moshi/utils/quantize.py, scripts/export_quantized.py, scripts/import_lightformer.py, scripts/update_repo.py
Adding support for depth transformer with weight sharing for some codebooks + low rank embeddings.
Also updating the quantize export to support the new config.json paradigm.
=> Adding Lightformer

moshi/moshi/conditioners/base.py, moshi/moshi/models/loaders.py, moshi/moshi/run_inference.py, moshi/moshi/server.py
Now share code for condition between server and run inference
=> general condition for server and run inference

moshi_mlx/moshi_mlx/models/generate.py, moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/run_inference.py, moshi_mlx/pyproject.toml, moshi_mlx/requirements.txt, rust/Cargo.toml, rust/mimi-pyo3/Cargo.toml, rust/mimi-pyo3/src/lib.rs, rust/moshi-backend/Cargo.toml, scripts/import_mlx.py
=> Lightformer implementation for MLX

moshi/moshi/__init__.py, moshi/moshi/conditioners/base.py, moshi/moshi/models/lm.py, moshi/moshi/modules/conv.py, moshi/moshi/quantization/core_vq.py, moshi/moshi/utils/compile.py, moshi/pyproject.toml, moshi_mlx/pyproject.toml
=> Fix type torch for 2.6

rust/Cargo.toml, rust/mimi-pyo3/Cargo.toml, rust/moshi-backend/Cargo.toml, rust/moshi-cli/Cargo.toml, rust/moshi-cli/src/audio_io.rs, rust/moshi-core/src/lm_generate_multistream.rs
=> Bugfix for how delays are handled over the first few slices.

scripts/import_rust.py
=> Adapt the rust import script to support the lightformer.

rust/Cargo.toml, rust/mimi-pyo3/Cargo.toml, rust/moshi-backend/Cargo.toml, rust/moshi-cli/Cargo.toml, rust/moshi-core/src/lm.rs
=> Support low-rank embeddings in the rust implementation.

rust/Cargo.toml, rust/mimi-pyo3/Cargo.toml, rust/moshi-backend/Cargo.toml, rust/moshi-cli/Cargo.toml, rust/moshi-core/Cargo.toml
=> Share the rust dependencies at the workspace level.

rust/Cargo.toml
=> Bump the candle version to 0.8.3.

moshi_mlx/moshi_mlx/models/__init__.py, moshi_mlx/moshi_mlx/models/mimi.py, moshi_mlx/moshi_mlx/modules/__init__.py, moshi_mlx/moshi_mlx/modules/conv.py, moshi_mlx/moshi_mlx/modules/quantization.py, moshi_mlx/moshi_mlx/modules/seanet.py, moshi_mlx/moshi_mlx/modules/transformer.py, scripts/mimi_mlx.py
=> Add an MLX implementation for mimi

moshi/moshi/__init__.py, moshi/moshi/quantization/core_vq.py
Average buffer code for training, as most training codebases won't do it automatically.
=> Average buffers

moshi_mlx/moshi_mlx/__init__.py
=> Bump the moshi-mlx version to 0.2.2.

moshi/moshi/modules/streaming.py
I, @hbredin, confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
Fix a typo in set_streaming_detached docstring
=> Fix set_streaming_detached docstring typo

rust/mimi-pyo3/src/lib.rs, rust/moshi-core/src/lm.rs, rust/moshi-core/src/lm_generate.rs, rust/moshi-core/src/lm_generate_multistream.rs, rust/moshi-core/src/mimi.rs, rust/moshi-core/src/transformer.rs, rust/moshi-core/src/tts.rs, rust/moshi-core/src/tts_streaming.rs
=> Update the rust core crate.

moshi_mlx/moshi_mlx/__init__.py, moshi_mlx/pyproject.toml
=> Bump the moshi mlx version to 0.24.

moshi_mlx/moshi_mlx/__init__.py, moshi_mlx/moshi_mlx/local_web.py
=> Hibiki mlx real-time support

rust/Cargo.toml
=> Update to the latest candle version.

moshi/moshi/models/lm.py, moshi/moshi/models/loaders.py
=> Allow having different numbers of codebooks in the input/output.

moshi/moshi/models/loaders.py, scripts/import_pytorch.py
- [ x] Read CONTRIBUTING.md, and accept the CLA by including the provided snippet. We will not accept PR without this.
more generic import script for pytorch inference
=> new import script

rust/Cargo.lock, rust/Cargo.toml
=> Update candle to 0.9.0.

moshi/pyproject.toml, moshi_mlx/pyproject.toml
=> Pin sphn to 0.1.x

rust/Cargo.lock, rust/Cargo.toml, rust/mimi-pyo3/src/lib.rs, rust/moshi-backend/src/benchmark.rs, rust/moshi-backend/src/standalone.rs, rust/moshi-backend/src/stream_both.rs, rust/moshi-cli/src/gen.rs, rust/moshi-core/src/asr.rs, rust/moshi-core/src/batched_transformer.rs, rust/moshi-core/src/conditioner.rs, rust/moshi-core/src/conv.rs, rust/moshi-core/src/kv_cache.rs, rust/moshi-core/src/lib.rs, rust/moshi-core/src/lm.rs, rust/moshi-core/src/lm_generate.rs, rust/moshi-core/src/lm_generate_multistream.rs, rust/moshi-core/src/mimi.rs, rust/moshi-core/src/nn.rs, rust/moshi-core/src/seanet.rs, rust/moshi-core/src/streaming.rs, rust/moshi-core/src/transformer.rs, rust/moshi-core/src/tts.rs, rust/moshi-core/src/tts_streaming.rs
=> Rust update.

moshi/moshi/__init__.py, moshi/moshi/models/lm.py, moshi/moshi/modules/streaming.py, scripts/test_missing_data_lm.py
=> fix bug in lm exec mask execution

moshi/moshi/__init__.py, moshi/moshi/models/lm.py, moshi/moshi/models/lm_utils.py, moshi/moshi/models/loaders.py, moshi/moshi/utils/sampling.py, scripts/import_pytorch.py
supporting models with a second text stream input.
=> Supporting two stream models

rust/Cargo.lock, rust/Cargo.toml, rust/moshi-backend/src/stream_both.rs, rust/moshi-server/Cargo.toml, rust/moshi-server/build.rs, rust/moshi-server/src/asr.rs, rust/moshi-server/src/batched_asr.rs, rust/moshi-server/src/legacy_tts.rs, rust/moshi-server/src/lib.rs, rust/moshi-server/src/lm.rs, rust/moshi-server/src/main.rs, rust/moshi-server/src/metrics.rs, rust/moshi-server/src/mimi.rs, rust/moshi-server/src/protocol.rs, rust/moshi-server/src/py_module.rs, rust/moshi-server/src/py_module_post.rs, rust/moshi-server/src/tts.rs, rust/moshi-server/src/utils.rs, rust/moshi-server/tts.py, rust/moshi-server/voice.py
=> Add the new rust server

rust/Cargo.lock, rust/Cargo.toml
=> Bump the crate version to 0.6.0.

rust/Cargo.lock, rust/Cargo.toml, rust/moshi-server/src/main.rs, rust/moshi-server/tts.py, rust/moshi-server/uv.lock
=> Embed the config files in the moshi-server binary.

scripts/streaming_stt_timestamps.py
- [ x] Read CONTRIBUTING.md, and accept the CLA by including the provided snippet. We will not accept PR without this.
Reference code on extracting timestamps from the STT predictions.
=> Reference script for STT with timestamps

rust/Cargo.lock, rust/Cargo.toml
=> Update the hf-hub dependency.

moshi/moshi/models/lm.py
Adding on_text_logits_hook, which is supposed to be used for various controlled generation tricks -- effectively allows to modify the sampling probabilities and or sampling space.
=> Adding on_text_logits_hook

moshi_mlx/moshi_mlx/models/mimi.py, moshi_mlx/moshi_mlx/modules/conv.py, moshi_mlx/moshi_mlx/modules/quantization.py, moshi_mlx/moshi_mlx/run_tts.py
=> Another mimi mlx fix.

moshi_mlx/moshi_mlx/run_tts.py
=> Add a quantization option for the mlx tts.

moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/run_tts.py
=> Move the mlx pytorch loader.

moshi_mlx/moshi_mlx/__init__.py, moshi_mlx/moshi_mlx/models/tts.py
=> Add some hooks to handle streaming.

moshi_mlx/moshi_mlx/models/tts.py
=> Add the on_frame callback to moshi mlx too.

moshi_mlx/moshi_mlx/__init__.py
=> Bump the mlx version.

rust/moshi-server/pyproject.toml, rust/moshi-server/uv.lock
=> Bump the moshi dependency used on the rust side to 0.2.8.

moshi_mlx/moshi_mlx/local_web.py, moshi_mlx/pyproject.toml
=> Fix the local-web MLX example + port to sphn 0.2.

moshi/moshi/__init__.py
=> Bump the version number for moshi.

rust/Cargo.lock, rust/Cargo.toml, rust/moshi-core/src/wav.rs, rust/moshi-server/Cargo.toml, rust/moshi-server/pyproject.toml, rust/moshi-server/src/asr.rs, rust/moshi-server/src/batched_asr.rs, rust/moshi-server/src/main.rs, rust/moshi-server/src/py_module.rs, rust/moshi-server/src/tts_preprocess.rs, rust/moshi-server/src/utils.rs, rust/moshi-server/uv.lock
=> Update to the latest upstream rust version.

moshi_mlx/moshi_mlx/models/generate.py
=> Apply the softmax to the extra-heads output in moshi_mlx.

moshi/moshi/__init__.py, moshi/moshi/models/loaders.py, moshi/moshi/models/tts.py, moshi/moshi/quantization/vq.py, scripts/import_pytorch.py
Add supports for internal multistream models.
=> Adding support for multistream models (experimental)

moshi/moshi/__init__.py, moshi/moshi/models/tts.py
=> fix bug in tts with reduced nq and adding py.typed file

rust/moshi-server/batched_asr.py, rust/moshi-server/src/main.rs, rust/moshi-server/src/py_basr_module.rs
=> Import upstream changes (pyo3 batched asr).

configs/stt_1b_enfr.json, configs/stt_2.6b_en.json, moshi/moshi/models/loaders.py, scripts/import_pytorch.py
=> Exporting STT models

moshi_mlx/moshi_mlx/__init__.py, moshi_mlx/moshi_mlx/models/generate.py, moshi_mlx/moshi_mlx/models/lm.py, moshi_mlx/moshi_mlx/models/mimi.py, moshi_mlx/moshi_mlx/models/tts.py, moshi_mlx/moshi_mlx/modules/transformer.py, moshi_mlx/moshi_mlx/utils/sampling.py
I, CarmenBach, confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
Introduces support for batching in the MLX implementation of Moshi.
Warning: this change may break compatibility with certain scripts that rely on internal implementation details, especially those that do more than simply call the core functions.
=> Add batching support to the MLX implementation

rust/moshi-server/tts.py
=> Configurable padding bonus.

.github/actions/moshi_build/action.yml, .pre-commit-config.yaml, moshi_mlx/moshi_mlx/local_web.py, moshi_mlx/moshi_mlx/models/mimi.py, moshi_mlx/moshi_mlx/models/tts.py, moshi_mlx/moshi_mlx/modules/__init__.py, moshi_mlx/moshi_mlx/modules/conditioner.py, moshi_mlx/moshi_mlx/modules/conv.py, moshi_mlx/moshi_mlx/modules/kv_cache.py, moshi_mlx/moshi_mlx/modules/quantization.py, moshi_mlx/moshi_mlx/modules/transformer.py, moshi_mlx/moshi_mlx/run_inference.py, moshi_mlx/moshi_mlx/run_tts.py, moshi_mlx/moshi_mlx/utils/loaders.py
=> Apply ruff formatting to moshi-mlx.

rust/moshi-server/src/py_module.rs
=> Only handle the model output after a proper init.

.github/actions/rust_build/action.yml
=> Use the new action to install the rust toolchain in the CI.
