kyutai-labs/moshi

- moshi/pyproject.toml
- moshi_mlx/moshi_mlx/local.py
- moshi_mlx/pyproject.toml
I, Erik Bjäreholt (@ErikBjare), confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
With this change you can now install moshi with:
- `pipx install moshi` (once it's on PyPI)
- `pipx install -e ./moshi/moshi` (which I tested)
This wasn't possible before since pipx requires a valid entrypoint to allow installation.
> added `moshi-*` scripts/entrypoints to pyproject.toml

- .github/workflows/rustymimi-ci.yml
The rustymimi bits of the CI are only useful when making a release of rustymimi so constrain the form of the tag required to run this.
> Avoid running the rustymimi CI on each commit.

- rust/mimi-pyo3/Cargo.toml
- rust/mimi-pyo3/src/lib.rs
- rust/moshi-backend/Cargo.toml
Currently the max-seq-len for the mimi transformer in mimi-pyo3 was set to 4096 resulting in only ~2min30s of conversation. Bump this to a default of 8192 to reach 5 mins and make it configurable just in case.
> Increase max_seq_len for mimi-pyo3 and make it configurable.

- moshi_mlx/moshi_mlx/local.py
- moshi_mlx/moshi_mlx/local_web.py
- moshi_mlx/pyproject.toml
- moshi_mlx/requirements.txt
Allow for longer sessions in moshi-mlx:
- Switch to rustymimi 0.2.2 where the max-seq-len is 8192 rather than 4096 allowing for 5min40s of conversations (as the mimi transformer runs at 25Hz).
- Set the default seq len to 4000 for the main generation routine.
> Allow longer conversations with mlx.

- FAQ.md
- moshi_mlx/moshi_mlx/local_web.py
- rust/README.md
This makes it easier to run on remote boxes, e.g. for #106
> Add an optional flag to use https on macos.

- rust/Cargo.toml
- rust/mimi-pyo3/Cargo.toml
- rust/moshi-backend/Cargo.toml
Upgrade candle to 0.7.1 so as to support cuda 12.6 and the new rotating kv cache.
> Upgrade candle to 0.7.1.

- README.md
- client/Dockerfile
- docker-compose.yml
- moshi/Dockerfile
```
I, @codearranger, confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
```
```
$ pre-commit run --all-files
flake8 on moshi package..................................................Passed
pyright on moshi package.................................................Passed
flake8 on moshi_mlx package..............................................Passed
pyright on moshi_mlx package.............................................Passed
```
Added Dockerfiles and docker compose to run the service on a Linux with the NVIDIA Container Toolkit
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
```docker compose up```
> Dockerized

- .gitignore
- moshi/moshi/modules/conv_test.py
- moshi/moshi/modules/seanet_test.py
- moshi/pyproject.toml
- moshi/requirements.txt
- [ X ] Read CONTRIBUTING.md, and accept the CLA by including the provided snippet. We will not accept PR without this.
- [ X ] Run pre-commit hook.
- [ X ] If you changed Rust code, run `cargo check`, `cargo clippy`, `cargo test`.
Add unit tests to check that the following submodules are causal and streamable:
* StreamingConv1d
* StreamingConvTranspose1d
* SEANetResnetBlock
* SEANetDecoder
Please see [the related issue](https://github.com/kyutai-labs/moshi/issues/134) for more context.
I, jerryli27, confirm that I have read and understood the terms of the CLA of Kyutai-labs, as outlined in the repository's CONTRIBUTING.md, and I agree to be bound by these terms.
> Add unit tests to ensure submodules are causal and streamable

- moshi/moshi/quantization/core_vq.py
- moshi/moshi/quantization/vq.py
VQ in the initial release didn't contain the code for the training, now it does!
> Making VQ training ready

- moshi/moshi/__init__.py
- moshi/moshi/models/lm.py
- moshi/moshi/modules/streaming.py
- moshi/moshi/modules/transformer.py
Depformer was never set in streaming mode which explain deterioration in quality in the CUDA demo (weights from first cb used all the way + no kv cache on previous cb...). Sorry about that, I'm quite surprised how it still somehow worked not so bad despite that pretty massive change.
Also fixing a bug in the KVCache, not as bad, would only have impact when wrapping around based on unit tests I ran on the internal codebase.
Update: after further review, the bug had no impact except if sin embeddings were to be used in the depformer which is not the case. This is because the original function was a mess and still properly put any children of Depformer in streaming mode even if Depformer itself was not streaming
> Fix streaming propagate + fixing bug in KV Cache

- rust/moshi-backend/Cargo.toml
- rust/moshi-backend/src/benchmark.rs
- rust/moshi-backend/src/main.rs
- rust/moshi-backend/src/standalone.rs
- rust/moshi-backend/src/stream_both.rs
> More internal changes merge.

- scripts/import_mlx.py
When converting the recently released Japanese version of Moshi at https://huggingface.co/nu-dialogue/j-moshi-ext to MLX, there was a tensor size mismatch error due to the converted model now using `n_q_main` for Depth transformer.
You can try out the MLX converted model with using this script by running `python -m moshi_mlx.local --hf-repo akkikiki/j-moshi-ext-mlx`.
> Fix a potential issue in mlx import when importing pytorch safetensor model

- moshi/moshi/client.py
- moshi/moshi/server.py
- [x ] Run pre-commit hook.
The first frame from Mimi is ignored by the model, but could contain important patterns on which the model rely, due to the padding. This will reset the state of Mimi after the first frame. Not the cleanest but should do the job.
> Skip initial frame in Mimi

- .gitignore
- README.md
- moshi/moshi/__init__.py
- moshi/moshi/models/lm.py
- moshi/moshi/models/loaders.py
- moshi/moshi/modules/gating.py
- moshi/moshi/modules/transformer.py
- moshi/moshi/run_inference.py
- moshi/moshi/server.py
- moshi/moshi/utils/quantize.py
- moshi/pyproject.toml
- scripts/export_quantized.py
Adding Moshi q8 with bitsandbytes, not clear if there is no loss of IQ in the model, but it runs.
> Adding Q8 quantization with bitsandbytes

- moshi/moshi/utils/quantize.py
- moshi/pyproject.toml
- [x ] Run pre-commit hook.
- [ x] If you changed Rust code, run `cargo check`, `cargo clippy`, `cargo test`.
bnb is not available on OSX (or at least juste a really old version with all the symbols missing), so making bnb only required on linux.
> Lazy bnb import as it is not available in OSX

- moshi_mlx/moshi_mlx/__init__.py
- moshi_mlx/moshi_mlx/models/lm.py
- moshi_mlx/moshi_mlx/run_inference.py
- moshi_mlx/pyproject.toml
- moshi_mlx/requirements.txt
- Bump the version number.
- Avoid the buggy teacher forcing.
- Add some properties to get the number of generated/other audio codebooks.
- Update the mlx version.
> Various MLX tweaks.

- moshi_mlx/moshi_mlx/models/mimi.py
- moshi_mlx/moshi_mlx/modules/conv.py
- moshi_mlx/moshi_mlx/modules/seanet.py
- scripts/mimi_mlx.py
> Streaming implementation for mimi on mlx

- rust/moshi-core/src/transformer.rs
> Include some recent transformer changes.

- moshi/README.md
- moshi/moshi/__init__.py
- moshi/moshi/models/compression.py
- moshi/moshi/models/lm.py
- moshi/moshi/modules/conv.py
- moshi/moshi/modules/rope.py
- moshi/moshi/modules/seanet.py
- moshi/moshi/modules/streaming.py
- moshi/moshi/modules/transformer.py
- moshi/moshi/utils/compile.py
- scripts/moshi_benchmark.py
- scripts/test_missing_data.py
Add execution masks + some refactoring allowing for Convs to be CUDA Graphed.
What we are losing is the ability to pass in arbitrary amount of audio, now the end user is responsible for buffering. When running on CUDA, with CUDAGraph activated ( the default), one should also always pass the same amount of audio.
> executation masks

- moshi_mlx/moshi_mlx/models/mimi.py
- moshi_mlx/moshi_mlx/modules/__init__.py
- moshi_mlx/moshi_mlx/modules/quantization.py
In the recent versions of mlx (at least in 0.26) the update callback is not called recursively on submodules whereas this used to be the case in older versions. We relied on this to update some of the codebook parameters, instead the update is now triggered explicitely when loading the pytorch weights (the downside is that nothing will happen when loading non-pytorch weights for now).
> Fix mimi for the recent versions of MLX.

- moshi/moshi/models/lm.py
… depformer
audio_hook was not called when skipping the depformer, but the code was expecting it. seems to have been broken for a while. I figured the cleanest was to always call the hook
> fix bug when using a prefix in the tts
